baseURL = "https://boys-love.club/"
defaultContentLanguage = "zh"
disableHugoGeneratorInject = true
enableGitInfo = false
languageCode = "zh-cn"
theme = "HN-hugo"
title = "Boy's Love"
themesDir = "../../"

[languages]
[languages.zh]
languageName = "繁體"
weight = 2
[languages.zht]
languageName = "简体"
weight = 1
[languages.zht.params]
js = []
links = [
  {name = "主頁", url = "/"},
  {name = "博客", url = "/post/"},
]

[imaging]
quality = 100

[params]
js = []
links = [
  {name = "主页", url = "/"},
  {name = "博客", url = "/post/"},
]
